export interface ProgramPromptItem {
  id: string;
  program_slug: string;
  category: string;
  title: string;
  prompt_text: string;
  description?: string;
  tags?: string[];
  is_active: boolean;
  sort_order: number;
  created_at?: string;
  updated_at?: string;
}

export const INITIAL_IMAGE_STUDIO_PROMPTS: ProgramPromptItem[] = [
  // 1. 실사 포토리얼리즘 (10개)
  {
    id: "photo-1",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#한옥카페 인물",
    prompt_text: "서울 경복궁 한옥 카페에서 노트북으로 작업 중인 한복을 입은 20대 한국 여성, 따뜻한 오후 햇살",
    description: "인물과 한옥 배경의 8K 극사실적 포토리얼리즘",
    tags: ["실사", "한옥카페", "인물", "8K"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "photo-2",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#제주 감성 풍경",
    prompt_text: "제주도 해변 언덕 위 해질녘 노을빛 오션뷰 한옥 숙소와 감성적인 풍경",
    description: "제주도 해변 노을 오션뷰 감성 사진",
    tags: ["실사", "제주도", "오션뷰", "노을"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "photo-3",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#스튜디오 인물 컷",
    prompt_text: "도도한 시선의 20대 한국 남성 모델, 은은한 스튜디오 링 라이트 조명과 85mm 인물 포트레이트",
    description: "스튜디오 링라이트 85mm 남성 모델 포트레이트",
    tags: ["실사", "스튜디오", "포트레이트", "85mm"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "photo-4",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#비오는 서울야경",
    prompt_text: "비에 젖은 서울 강남대로 신호등 불빛과 우산을 쓴 사람들의 몽환적인 포토리얼 포트레이트",
    description: "비에 젖은 강남대로 서울 도심 야경",
    tags: ["실사", "서울야경", "비", "강남대로"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "photo-5",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#봄날 벚꽃 피크닉",
    prompt_text: "벚꽃이 만개한 한강 공원 돗자리 위에서 웃고 있는 한국 젊은 남녀 커플 피크닉",
    description: "한강 공원 봄날 벚꽃 피크닉 커플",
    tags: ["실사", "벚꽃", "피크닉", "한강"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "photo-6",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#커피 브루잉 디테일",
    prompt_text: "핸드드립 커피가 유리 드립서버로 떨어지는 순간의 극사실적 클로즈업 사진",
    description: "핸드드립 커피 순간 포착 클로즈업",
    tags: ["실사", "커피", "핸드드립", "클로즈업"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "photo-7",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#모던 럭셔리 세단",
    prompt_text: "어두운 터널 속을 질주하는 블랙 럭셔리 스포츠 세단의 사이드 뷰 헤드라이트 궤적",
    description: "어두운 터널 스포츠 세단 사이드 뷰",
    tags: ["실사", "자동차", "세단", "헤드라이트"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "photo-8",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#가을 산책길 인물",
    prompt_text: "가을 단풍 숲길을 걷는 갈색 코트 차림의 한국 여성, 바스락거리는 낙엽 질감",
    description: "가을 단풍 숲길 여성 인물 포토",
    tags: ["실사", "가을", "단풍", "숲길"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "photo-9",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#럭셔리 워치 화보",
    prompt_text: "고급 매트 블랙 배경 위 실버 기계식 시계의 정교한 톱니바퀴 디테일 컷",
    description: "매트 블랙 배경 고급 실버 기계식 시계",
    tags: ["실사", "시계", "제품화보", "디테일"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "photo-10",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#해질녘 파도 서핑",
    prompt_text: "해질녘 분홍빛 바다 파도를 타는 서퍼의 다이내믹한 8K 순간 포착",
    description: "해질녘 바다 파도 타는 서퍼 8K",
    tags: ["실사", "서핑", "해질녘", "8K"],
    is_active: true,
    sort_order: 10,
  },

  // 2. 3D 디지털 아트 (10개)
  {
    id: "3d-1",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 마케팅 아이콘",
    prompt_text: "혁신적인 스마트폰과 신용카드가 떠있는 3D 미니멀 클레이 아트 마케팅 아이콘 세트",
    description: "3D 미니멀 클레이 아트 스마트폰 마케팅 아이콘",
    tags: ["3D", "마케팅", "아이콘", "스마트폰"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "3d-2",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#픽사풍 귀여운 캐릭터",
    prompt_text: "동글동글한 안경을 쓴 귀여운 3D 토끼 탐정 캐릭터, Pixar 애니메이션 렌더링",
    description: "픽사풍 3D 토끼 탐정 애니메이션 캐릭터",
    tags: ["3D", "픽사", "토끼", "애니메이션"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "3d-3",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#미래지향 3D 오브젝트",
    prompt_text: "투명한 글래스모피즘 큐브와 입체 가상화폐 3D 디스플레이 렌더",
    description: "투명 글래스모피즘 가상화폐 3D 렌더",
    tags: ["3D", "글래스모피즘", "가상화폐", "미래"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "3d-4",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 장난감 로봇",
    prompt_text: "귀여운 등불을 든 미니멀 3D 차콜 장난감 로봇 캐릭터",
    description: "등불 든 미니멀 3D 로봇 캐릭터",
    tags: ["3D", "로봇", "장난감", "미니멀"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "3d-5",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#입체 퐁퐁이 아일랜드",
    prompt_text: "구름 위에 떠있는 아기자기한 3D 장난감 마을과 무지개 동산",
    description: "구름 위 3D 장난감 마을 무지개 동산",
    tags: ["3D", "동화", "구름", "마을"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "3d-6",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 금융 백그라운드",
    prompt_text: "파스텔 톤 동전과 황금 열쇠가 날아다니는 금융 앱 3D 일러스트",
    description: "파스텔 톤 동전 3D 금융 앱 배경",
    tags: ["3D", "금융", "동전", "파스텔"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "3d-7",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 귀여운 디저트",
    prompt_text: "딸기 생크림 케이크와 알록달록 마카롱이 떠있는 3D 렌더링",
    description: "딸기 생크림 케이크와 마카롱 3D 렌더링",
    tags: ["3D", "디저트", "케이크", "마카롱"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "3d-8",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 우주선 비행",
    prompt_text: "알록달록한 아기 우주선이 반짝이는 별들 사이를 누비는 3D 그래픽",
    description: "알록달록 3D 아기 우주선 비행",
    tags: ["3D", "우주선", "별", "그래픽"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "3d-9",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 스마트 홈",
    prompt_text: "미니멀 아이콘 형태의 스마트 TV와 온도조절기가 조화를 이루는 3D 아트",
    description: "스마트 TV 3D 아이콘 미니멀 아트",
    tags: ["3D", "스마트홈", "가전", "아이콘"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "3d-10",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 동물 동화 캐릭터",
    prompt_text: "책 읽는 귀여운 3D 아기 곰돌이 캐릭터, 부드러운 3D 질감",
    description: "책 읽는 귀여운 3D 곰돌이 캐릭터",
    tags: ["3D", "곰돌이", "동화", "캐릭터"],
    is_active: true,
    sort_order: 10,
  },

  // 3. 감성 패션 화보 (10개)
  {
    id: "fashion-1",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#패션 룩북 화보",
    prompt_text: "모던한 미니멀 백그라운드 스튜디오에서 봄 신상 트렌치코트를 입은 모델의 패션 잡지 화보",
    description: "스튜디오 트렌치코트 패션 룩북 화보",
    tags: ["패션", "룩북", "트렌치코트", "잡지"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "fashion-2",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#보그 흑백 세련미",
    prompt_text: "Vogue 룩북 스타일, 드라마틱한 음영 대비가 돋보이는 모던 하이패션 포즈의 여성 모델",
    description: "Vogue 룩북 하이패션 흑백 포즈",
    tags: ["패션", "보그", "흑백", "하이패션"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "fashion-3",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#하이엔드 주얼리 컷",
    prompt_text: "고급스러운 아크릴 무대 위 다이아몬드 목걸이와 패션 잡지 커버컷 조명 연출",
    description: "다이아몬드 목걸이 잡지 커버 조명",
    tags: ["패션", "주얼리", "다이아몬드", "커버컷"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "fashion-4",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#네온 스트리트 패션",
    prompt_text: "밤거리 도심 속 힙한 스트릿웨어와 선글라스를 착용한 모델의 감성 화보",
    description: "도심 밤거리 힙한 스트릿웨어 화보",
    tags: ["패션", "스트릿웨어", "네온", "선글라스"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "fashion-5",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#미니멀 린넨 패션",
    prompt_text: "베이지 린넨 수트를 입은 한국 남성 모델의 차분하고 감성적인 인물 스냅",
    description: "린넨 수트 한국 남성 모델 인물 스냅",
    tags: ["패션", "린넨", "수트", "스냅"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "fashion-6",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#레트로 엘레강스",
    prompt_text: "70년대 클래식 무드의 드레스를 입은 모델과 레트로 가구 조화",
    description: "70년대 클래식 무드 레트로 드레스",
    tags: ["패션", "레트로", "70년대", "드레스"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "fashion-7",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#컬러 블록 에디토리얼",
    prompt_text: "강렬한 레드와 블루 배경이 대조를 이루는 아방가르드 패션 화보",
    description: "강렬한 레드 블루 아방가르드 패션 화보",
    tags: ["패션", "컬러블록", "아방가르드", "화보"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "fashion-8",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#하이패션 뷰티 포트레이트",
    prompt_text: "글로시한 입술과 매끈한 피부 디테일이 강조된 뷰티 매거진 커버 컷",
    description: "뷰티 매거진 커버 뷰티 포트레이트",
    tags: ["패션", "뷰티", "매거진", "포트레이트"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "fashion-9",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#스튜디오 그림자 예술",
    prompt_text: "블라인드 사이로 새어 나오는 슬릿 조명과 인물의 감각적인 실루엣",
    description: "블라인드 슬릿 조명 실루엣 예술",
    tags: ["패션", "그림자", "조명", "실루엣"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "fashion-10",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#실크 드레스 댄스",
    prompt_text: "바람에 흩날리는 붉은 실크 드레스를 입고 무용하는 모델의 역동적인 컷",
    description: "붉은 실크 드레스 무용 역동적 컷",
    tags: ["패션", "실크드레스", "무용", "역동적"],
    is_active: true,
    sort_order: 10,
  },

  // 4. 벡터 일러스트 (10개)
  {
    id: "vec-1",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#벡터 제품 일러스트",
    prompt_text: "친환경 오가닉 코스메틱 화장품 병과 나뭇잎 요소가 조화로운 벡터 평면 일러스트레이션",
    description: "오가닉 코스메틱 화장품 벡터 평면 일러스트",
    tags: ["벡터", "화장품", "오가닉", "평면"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "vec-2",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#IT 스타트업 캐릭터",
    prompt_text: "노트북으로 코딩 중인 젊은 개발자 팀, 선명한 아웃라인과 모던 벡터 스타일",
    description: "코딩 개발자 팀 모던 벡터 스타트업",
    tags: ["벡터", "스타트업", "개발자", "코딩"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "vec-3",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#도시 생활 플랫 카드",
    prompt_text: "커피를 들고 도심 공원을 산책하는 사람들의 세련된 flat vector 그래픽",
    description: "도심 공원 산책 세련된 flat vector",
    tags: ["벡터", "플랫아트", "산책", "공원"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "vec-4",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#여행 가방 벡터 아트",
    prompt_text: "세계 명소 라벨이 붙은 빈티지 여행 가방과 항공기 벡터 아이콘",
    description: "빈티지 여행 가방 항공기 벡터 아이콘",
    tags: ["벡터", "여행", "가방", "아이콘"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "vec-5",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#헬스 피트니스 벡터",
    prompt_text: "아령을 들고 운동하는 사람들의 밝고 건강한 평면 벡터 일러스트",
    description: "운동 피트니스 평면 벡터 일러스트",
    tags: ["벡터", "피트니스", "운동", "건강"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "vec-6",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#스마트시티 벡터",
    prompt_text: "자율주행 차와 태양광 판넬이 어우러진 친환경 스마트시티 벡터 포스터",
    description: "자율주행 스마트시티 친환경 벡터",
    tags: ["벡터", "스마트시티", "자율주행", "친환경"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "vec-7",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#배달 라이더 벡터",
    prompt_text: "오토바이를 타고 도시를 달리는 친근한 캐릭터 벡터 일러스트",
    description: "오토바이 배달 라이더 캐릭터 벡터",
    tags: ["벡터", "배달", "라이더", "캐릭터"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "vec-8",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#커피 브루잉 플랫아트",
    prompt_text: "원두와 드립포트가 정갈하게 배치된 모던 카페 벡터 그래픽",
    description: "원두 드립포트 모던 카페 벡터 그래픽",
    tags: ["벡터", "카페", "커피", "플랫아트"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "vec-9",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#음악 바이닐 벡터 아트",
    prompt_text: "LP판과 헤드폰이 아날로그 감성으로 배치된 팝아트 벡터",
    description: "LP판 헤드폰 아날로그 팝아트 벡터",
    tags: ["벡터", "음악", "LP판", "팝아트"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "vec-10",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#에코 그린 벡터",
    prompt_text: "지구를 품고 있는 나무와 나뭇잎들의 심플한 환경 캠페인 벡터",
    description: "지구 나무 환경 캠페인 심플 벡터",
    tags: ["벡터", "환경", "에코", "지구"],
    is_active: true,
    sort_order: 10,
  },

  // 5. 사이버펑크 네온 (10개)
  {
    id: "cyber-1",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#사이버펑크 서울야경",
    prompt_text: "네온사인 가득한 비 내리는 사이버펑크 서울 야경 속 트렌디한 한국 여성의 몽환적인 포트레이트",
    description: "네온사인 비 내리는 사이버펑크 서울 야경 포트레이트",
    tags: ["사이버펑크", "서울야경", "네온", "포트레이트"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "cyber-2",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#네온 라이더 스피드",
    prompt_text: "미래도시 네온 고속도로를 질주하는 사이버펑크 오토바이 라이더와 청색/자홍색 이펙트",
    description: "네온 고속도로 사이버펑크 오토바이 라이더",
    tags: ["사이버펑크", "오토바이", "네온", "라이더"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "cyber-3",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#미래형 해커 로봇",
    prompt_text: "신비로운 홀로그램 인터페이스를 조작하는 미래형 안드로이드 해커",
    description: "홀로그램 조작 안드로이드 해커",
    tags: ["사이버펑크", "해커", "안드로이드", "홀로그램"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "cyber-4",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#사이버펑크 차이나타운",
    prompt_text: "붉은 네온 등불과 한자가 반짝이는 미래 도시 골목의 고양이 포트레이트",
    description: "붉은 네온 등불 미래 도시 고양이 포트레이트",
    tags: ["사이버펑크", "고양이", "네온등불", "미래도시"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "cyber-5",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#네온 고글 사이보그",
    prompt_text: "투명 네온 고글을 쓰고 사이버네틱 임플란트를 이식한 힙합 아티스트",
    description: "네온 고글 사이버네틱 힙합 아티스트",
    tags: ["사이버펑크", "고글", "사이보그", "힙합"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "cyber-6",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#미래형 메카 기체",
    prompt_text: "안개 속 웅장하게 서 있는 거대 사이버펑크 전투 메카 로봇",
    description: "안개 속 거대 사이버펑크 전투 메카",
    tags: ["사이버펑크", "메카", "로봇", "전투"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "cyber-7",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#사이버펑크 술집 야경",
    prompt_text: "네온 조명 아래 홀로그램 술잔을 기울이는 사막의 여전사",
    description: "네온 조명 홀로그램 술잔 사막 여전사",
    tags: ["사이버펑크", "술집", "여전사", "네온"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "cyber-8",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#네온 비행 자동차",
    prompt_text: "초고층 빌딩 숲 사이를 누비는 붉은색 광원의 비행 자동차",
    description: "초고층 빌딩 비행 자동차 붉은 광원",
    tags: ["사이버펑크", "비행자동차", "빌딩", "네온"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "cyber-9",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#사이버펑크 브릿지",
    prompt_text: "자홍빛 안개 속에 휩싸인 미래 도시의 아치형 네온 대교",
    description: "자홍빛 안개 미래 도시 네온 대교",
    tags: ["사이버펑크", "대교", "네온", "미래도시"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "cyber-10",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#네온 닌자 아웃라인",
    prompt_text: "빛나는 사쿠라 네온 검을 든 스텔스 사이버 닌자",
    description: "사쿠라 네온 검 스텔스 사이버 닌자",
    tags: ["사이버펑크", "닌자", "네온", "사쿠라"],
    is_active: true,
    sort_order: 10,
  },

  // 6. 동양 수묵화 (10개)
  {
    id: "ink-1",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 한복 포트레이트",
    prompt_text: "은은한 수묵 먹선과 한지 질감 속 아련한 분위기의 한복 입은 선비와 매화 가지",
    description: "수묵 먹선 한지 질감 한복 선비 매화",
    tags: ["수묵화", "한복", "선비", "매화"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "ink-2",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#경복궁 수묵 산수화",
    prompt_text: "안개 낀 아침 삼각산과 경복궁 대웅전이 먹선의 짙고 옅음으로 그려진 동양 수묵화",
    description: "삼각산 경복궁 대웅전 동양 수묵화",
    tags: ["수묵화", "경복궁", "산수화", "삼각산"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "ink-3",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#달빛 매화 대나무",
    prompt_text: "둥근 은달빛 아래 대나무 잎과 흰 매화가 번진 조선 전통 수묵 채색화",
    description: "은달빛 대나무 흰 매화 수묵 채색화",
    tags: ["수묵화", "달빛", "대나무", "매화"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "ink-4",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 호랑이 기상",
    prompt_text: "용맹한 기세로 호효하는 호랑이의 기품 있는 먹선 수묵 드로잉",
    description: "용맹한 기세 호랑이 먹선 수묵 드로잉",
    tags: ["수묵화", "호랑이", "먹선", "드로잉"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "ink-5",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#한옥과 소나무 산수",
    prompt_text: "구름에 휩싸인 소나무 언덕 위 아담한 한옥 기와집의 은은한 수묵화",
    description: "구름 소나무 언덕 한옥 기와집 수묵화",
    tags: ["수묵화", "한옥", "소나무", "산수화"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "ink-6",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 연꽃 금붕어",
    prompt_text: "맑은 묵향 연못 속에 유유히 헤엄치는 붉은 금붕어와 연꽃 수묵 채색",
    description: "연못 붉은 금붕어 연꽃 수묵 채색",
    tags: ["수묵화", "금붕어", "연꽃", "연못"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "ink-7",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#풍류 가야금 선비",
    prompt_text: "계곡 정자 아래 가야금을 연주하는 선비의 운치 있는 동양화",
    description: "계곡 정자 가야금 연주 선비 동양화",
    tags: ["수묵화", "가야금", "선비", "정자"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "ink-8",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 학과 일출",
    prompt_text: "붉은 아침 해를 향해 날아오르는 두루미(학)의 고결한 먹선 붓터치",
    description: "붉은 아침 해 날아오르는 두루미 수묵화",
    tags: ["수묵화", "학", "일출", "두루미"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "ink-9",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#비 내리는 한양 수묵",
    prompt_text: "먹구름 낀 옛 한양 거리를 삿갓을 쓰고 걷는 나그네의 수묵 감성",
    description: "옛 한양 거리 삿갓 나그네 수묵 감성",
    tags: ["수묵화", "한양", "나그네", "비"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "ink-10",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 산사 안개",
    prompt_text: "겹겹이 싸인 청산 속 고즈넉한 산사의 종소리가 느껴지는 수묵 진경산수화",
    description: "청산 고즈넉한 산사 수묵 진경산수화",
    tags: ["수묵화", "산사", "진경산수화", "안개"],
    is_active: true,
    sort_order: 10,
  },

  // 7. 수채화 파스텔 (10개)
  {
    id: "water-1",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 파스텔 동화",
    prompt_text: "해질녘 분홍빛 노을 하늘 아래 동화 속 작은 목조 오두막과 꽃밭 풍경",
    description: "분홍빛 노을 동화 목조 오두막 꽃밭",
    tags: ["수채화", "파스텔", "동화", "오두막"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "water-2",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 고양이 감성",
    prompt_text: "창가 햇살 아래 졸고 있는 몽환적인 털 질감의 수채화 고양이 일러스트",
    description: "창가 햇살 수채화 고양이 일러스트",
    tags: ["수채화", "고양이", "햇살", "일러스트"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "water-3",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#파스텔 봄날 꽃길",
    prompt_text: "벚꽃잎이 날리는 시골 오솔길을 자전거로 달리는 아이의 맑은 수채화",
    description: "벚꽃 오솔길 자전거 아이 맑은 수채화",
    tags: ["수채화", "벚꽃", "자전거", "오솔길"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "water-4",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#파스텔 유니콘 꿈",
    prompt_text: "민트빛 하늘 속 은은한 수채화 물감이 번진 몽환적인 유니콘 동화",
    description: "민트빛 하늘 유니콘 동화 수채화",
    tags: ["수채화", "유니콘", "동화", "파스텔"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "water-5",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 수국 정원",
    prompt_text: "보랏빛 수국 꽃잎에 물방울이 촉촉히 맺힌 투명한 수채화 화법",
    description: "보랏빛 수국 물방울 투명 수채화",
    tags: ["수채화", "수국", "정원", "꽃"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "water-6",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#파스텔 바닷가 마을",
    prompt_text: "에메랄드 빛 바다와 알록달록한 파스텔 지붕이 어우러진 해안 마을",
    description: "에메랄드 바다 파스텔 지붕 해안 마을",
    tags: ["수채화", "바닷가", "파스텔", "마을"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "water-7",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 커피 한 잔",
    prompt_text: "김이 모락모락 나는 따뜻한 찻잔과 수채화 기법의 브런치 풍경",
    description: "따뜻한 찻잔 브런치 풍경 수채화",
    tags: ["수채화", "커피", "브런치", "찻잔"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "water-8",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#파스텔 밤하늘 은하수",
    prompt_text: "밤하늘 가득 반짝이는 파스텔 오로라와 은하수 아래 캠핑 텐트",
    description: "파스텔 오로라 은하수 캠핑 텐트",
    tags: ["수채화", "오로라", "은하수", "캠핑"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "water-9",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 아기 사슴",
    prompt_text: "숲속 들꽃 사이를 누비는 아기 사슴의 부드럽고 따스한 수채화",
    description: "숲속 들꽃 아기 사슴 따스한 수채화",
    tags: ["수채화", "아기사슴", "숲속", "들꽃"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "water-10",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#파스텔 빗방울 우산",
    prompt_text: "노란 우산을 쓴 소녀의 따스하고 감성적인 비 오는 날 수채화",
    description: "노란 우산 비 오는 날 감성 수채화",
    tags: ["수채화", "우산", "비오는날", "파스텔"],
    is_active: true,
    sort_order: 10,
  },

  // 8. 35mm 필름 (10개)
  {
    id: "film-1",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#35mm 빈티지 카페",
    prompt_text: "80년대 골목길 카페 야외 테라스에서 커피를 마시는 감성적인 빈티지 인물 컷",
    description: "80년대 테라스 카페 빈티지 35mm 컷",
    tags: ["필름", "35mm", "빈티지", "카페"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "film-2",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#레트로 야간 스냅",
    prompt_text: "Kodak Portra 400 필름 특유의 따뜻한 입자와 비 오는 밤 도쿄 골목 네온 스냅",
    description: "Kodak Portra 400 도쿄 골목 네온 스냅",
    tags: ["필름", "Kodak", "레트로", "스냅"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "film-3",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#여름 바다 필름 감성",
    prompt_text: "햇빛이 수면에 반사되는 청량한 여름 바닷가와 90년대 필름 카메라 질감",
    description: "청량한 여름 바닷가 90년대 필름 질감",
    tags: ["필름", "여름바다", "90년대", "필름카메라"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "film-4",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#레트로 올드카 여행",
    prompt_text: "노을빛 사막 도로 위에 멈춰선 클래식 올드카와 여행자의 필름 사진",
    description: "노을빛 사막 클래식 올드카 필름 포토",
    tags: ["필름", "올드카", "사막", "여행"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "film-5",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#70년대 아날로그 레코드",
    prompt_text: "아날로그 LP판을 들고 미소 짓는 뮤지션의 따스한 35mm 레트로 컷",
    description: "70년대 LP판 레트로 뮤지션 컷",
    tags: ["필름", "70년대", "LP판", "레트로"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "film-6",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#필름 빛갈라짐 인물",
    prompt_text: "숲속 틈새 햇살 아래 눈을 감은 인물의 오렌지빛 필름 플레어",
    description: "숲속 햇살 오렌지빛 필름 플레어 인물",
    tags: ["필름", "빛갈라짐", "플레어", "포트레이트"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "film-7",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#레트로 레스토랑 데이트",
    prompt_text: "네온 글라스와 빈티지 소파가 어우러진 80년대 레스토랑의 인물 사진",
    description: "80년대 레스토랑 빈티지 인물 데이트",
    tags: ["필름", "80년대", "레스토랑", "빈티지"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "film-8",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#아날로그 기차 창가",
    prompt_text: "달리는 기차 창가 밖 들판을 바라보는 인물의 아련한 필름 감성",
    description: "달리는 기차 창가 아련한 필름 포토",
    tags: ["필름", "기차", "창가", "여행"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "film-9",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#35mm 흑백 포토",
    prompt_text: "강렬한 그레인과 거친 질감이 살이있는 빈티지 흑백 스트리트 포토",
    description: "강렬한 그레인 빈티지 흑백 스트리트 포토",
    tags: ["필름", "흑백", "그레인", "스트리트"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "film-10",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#레트로 레코드 샵",
    prompt_text: "수많은 레코드판이 꽂힌 아날로그 상점에서 음악을 듣는 인물 컷",
    description: "아날로그 레코드 상점 음악 듣는 인물",
    tags: ["필름", "레코드샵", "아날로그", "음악"],
    is_active: true,
    sort_order: 10,
  },

  // 9. 클레이 스톱모션 (10개)
  {
    id: "clay-1",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#지점토 귀여운 공룡",
    prompt_text: "손맛 느껴지는 울퉁불퉁 지점토 질감의 알록달록 아기 공룡 스톱모션 인형",
    description: "울퉁불퉁 지점토 아기 공룡 스톱모션",
    tags: ["클레이", "스톱모션", "공룡", "지점토"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "clay-2",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 베이커리 빵",
    prompt_text: "따뜻한 오븐 속 귀여운 표정이 그려진 클레이 빵과 미니어처 주방",
    description: "귀여운 표정 클레이 빵 미니어처 주방",
    tags: ["클레이", "베이커리", "미니어처", "빵"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "clay-3",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 아기자기 마을",
    prompt_text: "아기자기한 클레이 스톱모션 미니어처 마을과 알록달록 자동차",
    description: "아기자기 미니어처 클레이 마을 자동차",
    tags: ["클레이", "미니어처", "마을", "스톱모션"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "clay-4",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#지점토 우주 비행사",
    prompt_text: "둥글둥글한 지점토 우주복을 입은 아기 우주 비행사 인형",
    description: "둥글둥글 지점토 아기 우주 비행사",
    tags: ["클레이", "우주비행사", "지점토", "우주"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "clay-5",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 펭귄 가족",
    prompt_text: "남극 얼음판 위에서 옹기종기 모여있는 클레이 펭귄 캐릭터들",
    description: "남극 얼음판 클레이 펭귄 캐릭터들",
    tags: ["클레이", "펭귄", "남극", "캐릭터"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "clay-6",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 햄버거 세트",
    prompt_text: "미니어처 지점토 치즈버거와 감자튀김 스톱모션 푸드 소품",
    description: "미니어처 지점토 치즈버거 감자튀김",
    tags: ["클레이", "햄버거", "푸드", "미니어처"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "clay-7",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 숲속 버섯 집",
    prompt_text: "알록달록한 지점토 버섯 지붕 집과 클레이 아기 요정",
    description: "알록달록 버섯 지붕 집 클레이 요정",
    tags: ["클레이", "버섯집", "요정", "숲속"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "clay-8",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 몬스터 밴드",
    prompt_text: "기타와 드럼을 연주하는 귀여운 클레이 몬스터 음악 밴드",
    description: "기타 드럼 연주 클레이 몬스터 밴드",
    tags: ["클레이", "몬스터", "밴드", "음악"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "clay-9",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 해적선 항해",
    prompt_text: "아기자기한 지점토 장난감 해적선과 손맛 넘치는 바다 파도",
    description: "아기자기 지점토 해적선 바다 파도",
    tags: ["클레이", "해적선", "바다", "항해"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "clay-10",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#클레이 크리스마스 트리",
    prompt_text: "반짝이는 방울과 눈사람 지점토 인형이 달린 트리 스톱모션",
    description: "눈사람 지점토 인형 크리스마스 트리",
    tags: ["클레이", "크리스마스", "트리", "눈사람"],
    is_active: true,
    sort_order: 10,
  },

  // 10. 웹툰 라인아트 (10개)
  {
    id: "toon-1",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#웹툰 주인공 액션",
    prompt_text: "강렬한 먹선 아웃라인과 셀 셰이딩이 돋보이는 한국 판타지 웹툰 주인공 소환 씬",
    description: "강렬한 먹선 아웃라인 판타지 웹툰 소환 씬",
    tags: ["웹툰", "라인아트", "판타지", "먹선"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "toon-2",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#학원물 웹툰 로맨스",
    prompt_text: "학교 복도 창가 햇살 아래 서로 바라보는 고등학생 남녀 웹툰 명장면",
    description: "학교 복도 햇살 고등학생 남녀 웹툰 명장면",
    tags: ["웹툰", "학원물", "로맨스", "학교"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "toon-3",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#도시 몬스터 웹툰",
    prompt_text: "서울 강남역 한복판에 나타난 거대 몬스터와 이에 맞서는 웹툰 히어로",
    description: "강남역 한복판 거대 몬스터 웹툰 히어로",
    tags: ["웹툰", "몬스터", "히어로", "강남역"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "toon-4",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#무협 웹툰 검사",
    prompt_text: "바람에 도포 자락이 날리는 조선 판타지 무협 웹툰의 검객",
    description: "도포 자락 날리는 조선 무협 웹툰 검객",
    tags: ["웹툰", "무협", "검객", "조선"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "toon-5",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#사이버 헌터 웹툰",
    prompt_text: "게이트가 열린 현대 도시에서 각성한 S급 헌터의 웹툰 일러스트",
    description: "현대 게이트 S급 헌터 각성 웹툰",
    tags: ["웹툰", "헌터", "게이트", "각성"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "toon-6",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#로맨스 판타지 영애",
    prompt_text: "화려한 영애 드레스를 입은 로맨스 판타지 웹툰 여주인공",
    description: "화려한 드레스 로판 웹툰 여주인공",
    tags: ["웹툰", "로판", "영애", "드레스"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "toon-7",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#음식 웹툰 먹방",
    prompt_text: "김이 모락모락 나는 떡볶이와 튀김이 먹음직스럽게 그려진 웹툰 컷",
    description: "김 나는 떡볶이 튀김 먹방 웹툰 컷",
    tags: ["웹툰", "음식", "떡볶이", "먹방"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "toon-8",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#스포츠 웹툰 슬램",
    prompt_text: "농구 코트 위에서 역동적으로 슛을 던지는 스포츠 웹툰 명장면",
    description: "농구 코트 슛 역동적 스포츠 웹툰 명장면",
    tags: ["웹툰", "스포츠", "농구", "슬램"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "toon-9",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#일상 인디 웹툰",
    prompt_text: "자취방에서 반려묘와 누워있는 소소한 일상 한국 웹툰 일러스트",
    description: "자취방 반려묘 소소한 일상 웹툰",
    tags: ["웹툰", "일상", "자취방", "반려묘"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "toon-10",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#스릴러 웹툰 인물",
    prompt_text: "어두운 조명 속 차가운 눈빛을 한 추리 웹툰 주인공 포트레이트",
    description: "어두운 조명 차가운 눈빛 추리 웹툰 주인공",
    tags: ["웹툰", "스릴러", "추리", "포트레이트"],
    is_active: true,
    sort_order: 10,
  },

  // 11. 건축 & 인테리어 (10개)
  {
    id: "arch-1",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#건축 인테리어",
    prompt_text: "통창 너머로 숲이 펼쳐지는 미니멀 우드 앤 콘크리트 고급 거실 인테리어 디자인",
    description: "통창 숲 오션뷰 미니멀 우드 콘크리트 거실",
    tags: ["건축", "인테리어", "미니멀", "거실"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "arch-2",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#모던 단독주택 외관",
    prompt_text: "ArchDaily 잡지 커버 스타일, 자연광과 노출 콘크리트 조화의 미니멀 모던 주택",
    description: "ArchDaily 노출 콘크리트 미니멀 주택 외관",
    tags: ["건축", "주택외관", "ArchDaily", "콘크리트"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "arch-3",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#호텔 리조트 수영장",
    prompt_text: "발리 리조트풍 인피니티 풀과 해질녘 오렌지빛 라이팅 디자인 공간",
    description: "발리 리조트풍 인피니티 풀 해질녘 조명",
    tags: ["건축", "리조트", "인피니티풀", "수영장"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "arch-4",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#북유럽 미니멀 주방",
    prompt_text: "대리석 아일랜드 식탁과 따뜻한 펜던트 조명이 돋보이는 모던 키친",
    description: "대리석 아일랜드 식탁 펜던트 조명 모던 주방",
    tags: ["건축", "주방", "키친", "북유럽"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "arch-5",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#공중정원 온실 스튜디오",
    prompt_text: "유리 온실 구조 속 수목이 가득한 생태 친화적 건축 오피스",
    description: "유리 온실 수목 오피스 건축 스튜디오",
    tags: ["건축", "온실", "오피스", "친환경"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "arch-6",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#자연광 테라스 서재",
    prompt_text: "나무 서가와 편안한 1인용 소파가 자연광을 받으며 놓인 서재",
    description: "나무 서가 자연광 소파 미니멀 서재",
    tags: ["건축", "서재", "자연광", "인테리어"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "arch-7",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#도심 펜트하우스 야경",
    prompt_text: "통유리창으로 도심 야경이 한눈에 들어오는 고급 펜트하우스 침실",
    description: "통유리창 도심 야경 고급 펜트하우스 침실",
    tags: ["건축", "펜트하우스", "야경", "침실"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "arch-8",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#일본식 미니멀 중정",
    prompt_text: "단풍나무와 자갈 정원이 바라보이는 정갈한 지다미 스타일 한옥/와시츠",
    description: "단풍나무 자갈 정원 정갈한 일본식 중정",
    tags: ["건축", "중정", "한옥", "와시츠"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "arch-9",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#미래형 갤러리 미술관",
    prompt_text: "곡선형 콘크리트 벽면과 천장 천창 라이팅이 예술적인 현대 미술관",
    description: "곡선형 콘크리트 천창 라이팅 현대 미술관",
    tags: ["건축", "미술관", "갤러리", "현대건축"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "arch-10",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#스파 바이오필릭 바스",
    prompt_text: "자연 석재 욕조와 대나무 숲 뷰가 차분함을 주는 바이오필릭 욕실",
    description: "자연 석재 욕조 대나무 숲 바이오필릭 욕실",
    tags: ["건축", "욕실", "스파", "바이오필릭"],
    is_active: true,
    sort_order: 10,
  },

  // 12. 다크 판타지 (10개)
  {
    id: "dark-1",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#다크판타지 웅장함",
    prompt_text: "어둡고 신비로운 고성 타워 위에서 붉은 마법 룬을 시전하는 검은 로브의 마법사",
    description: "어둡고 신비로운 고성 마법 룬 시전 마법사",
    tags: ["다크판타지", "고성", "마법사", "룬"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "dark-2",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#심연의 고딕 기사",
    prompt_text: "자색 안개 가득한 폐허 성당 앞 거대한 대검을 든 고딕 다크 판타지 기사",
    description: "자색 안개 폐허 성당 대검 고딕 기사",
    tags: ["다크판타지", "기사", "고딕", "대검"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "dark-3",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#용의 둥지 수호자",
    prompt_text: "용암이 흐르는 어두운 동굴 속 붉은 눈의 용과 고대 성물",
    description: "용암 동굴 붉은 눈의 용 고대 성물 수호자",
    tags: ["다크판타지", "용", "용암", "성물"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "dark-4",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#해골 왕좌 군주",
    prompt_text: "해골과 뼈로 조각된 고딕 왕좌에 앉아있는 안개 속 불사의 왕",
    description: "해골 뼈 조각 고딕 왕좌 불사의 왕",
    tags: ["다크판타지", "해골왕좌", "군주", "불사"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "dark-5",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#저주받은 숲 요정",
    prompt_text: "이끼 낀 거대한 고목과 신비로운 푸른 빛버섯이 자라는 잔혹 동화 숲",
    description: "이끼 고목 푸른 빛버섯 잔혹 동화 숲",
    tags: ["다크판타지", "요정", "잔혹동화", "숲"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "dark-6",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#타락한 천사의 날개",
    prompt_text: "붉은 핏빛 달 아래 흑색 날개를 펼치고 있는 타락 천사",
    description: "붉은 핏빛 달 흑색 날개 타락 천사",
    tags: ["다크판타지", "타락천사", "날개", "핏빛달"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "dark-7",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#네크로맨서 소환",
    prompt_text: "어두운 지하 묘지에서 푸른 영혼의 불꽃을 소환하는 주술사",
    description: "지하 묘지 푸른 영혼 불꽃 네크로맨서",
    tags: ["다크판타지", "네크로맨서", "지하묘지", "소환"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "dark-8",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#고딕 뱀파이어 성",
    prompt_text: "벼락이 치는 암벽 산 정상 위에 솟아있는 장엄한 고딕 뱀파이어 성",
    description: "벼락 암벽 산 정상 고딕 뱀파이어 성",
    tags: ["다크판타지", "뱀파이어", "고딕성", "벼락"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "dark-9",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#마법 연금술 랩",
    prompt_text: "보랏빛 물약이 끓고 고대 마도서가 넘겨지는 비밀 연금술사의 방",
    description: "보랏빛 물약 고대 마도서 연금술사의 방",
    tags: ["다크판타지", "연금술", "마도서", "마법"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "dark-10",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#룬 문자 마법검",
    prompt_text: "차가운 서리가 내린 검신 위에 룬 문자가 빛나는 신화 속의 검",
    description: "서리 내린 검신 룬 문자 마법검",
    tags: ["다크판타지", "마법검", "룬문자", "신화"],
    is_active: true,
    sort_order: 10,
  },

  // 13. 미니멀 플랫 아트 (10개)
  {
    id: "flat-1",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#미니멀 여행 포스터",
    prompt_text: "제주 돌하르방과 조용한 해변을 감각적인 컬러 블록으로 표현한 모던 아트 포스터",
    description: "제주 돌하르방 해변 모던 컬러 블록 포스터",
    tags: ["미니멀", "플랫아트", "제주", "포스터"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "flat-2",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#플랫 팝아트 인물",
    prompt_text: "강렬한 비비드 컬러와 단순한 기하학 도형으로 디자인된 인물 포스터",
    description: "강렬한 비비드 컬러 기하학 인물 포스터",
    tags: ["미니멀", "팝아트", "플랫아트", "비비드"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "flat-3",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#모던 미드센추리 가구",
    prompt_text: "60년대 미드센추리 모던 가구와 플랫 그래픽 일러스트",
    description: "60년대 미드센추리 모던 가구 플랫 일러스트",
    tags: ["미니멀", "미드센추리", "가구", "플랫아트"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "flat-4",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#음악 바이닐 그래픽",
    prompt_text: "LP 플레이어와 턴테이블이 강렬한 컬러 콘트라스트로 표현된 플랫 그래픽",
    description: "LP 플레이어 턴테이블 플랫 콘트라스트 그래픽",
    tags: ["미니멀", "LP판", "음악", "플랫아트"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "flat-5",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#커피 모노톤 일러스트",
    prompt_text: "모노톤 브라운 톤의 그래픽 도형으로 구성된 모던 커피 브랜딩 포스터",
    description: "모노톤 브라운 도형 모던 커피 브랜딩 포스터",
    tags: ["미니멀", "커피", "모노톤", "브랜딩"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "flat-6",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#시티 브리즈 플랫",
    prompt_text: "선글라스를 끼고 야자수 도로를 달리는 자동차의 모던 미니멀 플랫 아트",
    description: "야자수 도로 자동차 모던 미니멀 플랫 아트",
    tags: ["미니멀", "시티브리즈", "자동차", "플랫아트"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "flat-7",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#스마트 파이낸스 일러스트",
    prompt_text: "파스텔 계열의 평면 기하학 도형으로 구성된 스마트 금융 아트",
    description: "파스텔 평면 기하학 스마트 금융 아트",
    tags: ["미니멀", "금융", "파스텔", "플랫아트"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "flat-8",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#네이처 가드닝 아트",
    prompt_text: "가위와 화분이 아기자기한 벡터 평면으로 배치된 모던 가드닝 포스터",
    description: "아기자기 화분 가드닝 모던 플랫 포스터",
    tags: ["미니멀", "가드닝", "에코", "플랫아트"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "flat-9",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#스페이스 우주 플랫",
    prompt_text: "신비로운 원형 행성들과 은하수가 단순한 선과 색면으로 구성된 우주 아트",
    description: "원형 행성 은하수 단순 선 색면 우주 아트",
    tags: ["미니멀", "우주", "행성", "플랫아트"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "flat-10",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#북커버 미니멀 그래픽",
    prompt_text: "세련된 타이포그래피와 대담한 비대칭 컬러 면 분할로 이루어진 책 커버 디자인",
    description: "세련된 타이포그래피 비대칭 컬러 면 책 커버",
    tags: ["미니멀", "북커버", "타이포그래피", "디자인"],
    is_active: true,
    sort_order: 10,
  },

  // 기타 프로그램 샘플
  {
    id: "blog-1",
    program_slug: "ai-auto-blog",
    category: "SEO 가이드",
    title: "초보자 가이드 작성",
    prompt_text: "당신은 전문 IT 기술 블로거입니다. '{keyword}'에 대해 SEO 구조로 제목과 서론, 본문 3가지 팁, 결론을 작성하세요.",
    description: "SEO 블로그 원문 작성 템플릿",
    tags: ["SEO", "블로그", "가이드"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "threads-1",
    program_slug: "auto-threads-posting",
    category: "바이럴 숏폼",
    title: "직장인 공감 텍스트",
    prompt_text: "Threads 바이럴 문구를 만듭니다. 가독성을 높인 숏폼 한글 텍스트와 명언 1줄로 마무리하세요.",
    description: "Threads 알고리즘 맞춤 숏폼",
    tags: ["Threads", "바이럴", "공감"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "music-1",
    program_slug: "music-automation",
    category: "K-POP 신스팝",
    title: "청량한 여름 밤 신스팝",
    prompt_text: "Upbeat Korean Synthpop, bright synthesizer melody, punchy bassline, catchy chorus, energetic vocal, 128 bpm",
    description: "Suno AI 프롬프트 예시",
    tags: ["Suno", "신스팝", "K-POP"],
    is_active: true,
    sort_order: 1,
  }
];
