export interface ProgramPromptItem {
  id: string;
  program_slug: string;
  category: string;
  title: string;
  prompt_text: string;
  description?: string;
  tags?: string[];
  is_active: boolean;
  sort_order: number;
  created_at?: string;
  updated_at?: string;
}

export const INITIAL_IMAGE_STUDIO_PROMPTS: ProgramPromptItem[] = [
  // 1. 실사 포토리얼리즘 (10개)
  {
    id: "img-photo-1",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#한옥카페 인물",
    prompt_text: "서울 경복궁 한옥 카페에서 노트북으로 작업 중인 한복을 입은 20대 한국 여성, 따뜻한 오후 햇살",
    description: "인물과 한옥 배경의 고화질 8K 실사 포트레이트",
    tags: ["실사", "한옥카페", "인물", "8K"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "img-photo-2",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#제주 감성 풍경",
    prompt_text: "제주도 해변 언덕 위 해질녘 노을빛 오션뷰 한옥 숙소와 감성적인 풍경",
    description: "제주 해변과 오션뷰 노을 감성 포토",
    tags: ["실사", "제주도", "노을", "풍경"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "img-photo-3",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#스튜디오 인물 컷",
    prompt_text: "도도한 시선의 20대 한국 남성 모델, 은은한 스튜디오 링 라이트 조명과 85mm 인물 포트레이트",
    description: "스튜디오 85mm 렌즈 인물 사진",
    tags: ["실사", "스튜디오", "포트레이트", "남성모델"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "img-photo-4",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#비오는 서울야경",
    prompt_text: "비에 젖은 서울 강남대로 신호등 불빛과 우산을 쓴 사람들의 몽환적인 포토리얼 포트레이트",
    description: "서울 도심 야경 및 우산 인물 실사",
    tags: ["실사", "서울야경", "비", "강남대로"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "img-photo-5",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#봄날 벚꽃 피크닉",
    prompt_text: "벚꽃이 만개한 한강 공원 돗자리 위에서 웃고 있는 한국 젊은 남녀 커플 피크닉",
    description: "한강 벚꽃 봄날 야외 피크닉 커플",
    tags: ["실사", "벚꽃", "한강공원", "피크닉"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "img-photo-6",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#커피 브루잉 디테일",
    prompt_text: "핸드드립 커피가 유리 드립서버로 떨어지는 순간의 극사실적 클로즈업 사진",
    description: "핸드드립 커피 클로즈업 디테일",
    tags: ["실사", "커피", "핸드드립", "클로즈업"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "img-photo-7",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#모던 럭셔리 세단",
    prompt_text: "어두운 터널 속을 질주하는 블랙 럭셔리 스포츠 세단의 사이드 뷰 헤드라이트 궤적",
    description: "터널 럭셔리 자동차 라이트 궤적",
    tags: ["실사", "자동차", "세단", "터널"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "img-photo-8",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#가을 산책길 인물",
    prompt_text: "가을 단풍 숲길을 걷는 갈색 코트 차림의 한국 여성, 바스락거리는 낙엽 질감",
    description: "가을 단풍 숲길 산책 포토",
    tags: ["실사", "가을", "단풍", "산책"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "img-photo-9",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#럭셔리 워치 화보",
    prompt_text: "고급 매트 블랙 배경 위 실버 기계식 시계의 정교한 톱니바퀴 디테일 컷",
    description: "매트 블랙 배경 기계식 시계",
    tags: ["실사", "시계", "제품화보", "럭셔리"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "img-photo-10",
    program_slug: "ai-image-studio",
    category: "실사 포토리얼리즘",
    title: "#해질녘 파도 서핑",
    prompt_text: "해질녘 분홍빛 바다 파도를 타는 서퍼의 다이내믹한 8K 순간 포착",
    description: "해질녘 바다 서핑 8K 액션 샷",
    tags: ["실사", "서핑", "바다", "해질녘"],
    is_active: true,
    sort_order: 10,
  },

  // 2. 3D 디지털 아트 (10개)
  {
    id: "img-3d-1",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 마케팅 아이콘",
    prompt_text: "혁신적인 스마트폰과 신용카드가 떠있는 3D 미니멀 클레이 아트 마케팅 아이콘 세트",
    description: "앱 마케팅용 3D 클레이 아이콘",
    tags: ["3D", "마케팅", "아이콘", "스마트폰"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "img-3d-2",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#픽사풍 귀여운 캐릭터",
    prompt_text: "동글동글한 안경을 쓴 귀여운 3D 토끼 탐정 캐릭터, Pixar 애니메이션 렌더링",
    description: "픽사 3D 스타일 토끼 캐릭터",
    tags: ["3D", "픽사", "캐릭터", "애니메이션"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "img-3d-3",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#미래지향 3D 오브젝트",
    prompt_text: "투명한 글래스모피즘 큐브와 입체 가상화폐 3D 디스플레이 렌더",
    description: "글래스모피즘 미래 지향 3D 디스플레이",
    tags: ["3D", "글래스모피즘", "미래", "가상화폐"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "img-3d-4",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 장난감 로봇",
    prompt_text: "귀여운 등불을 든 미니멀 3D 차콜 장난감 로봇 캐릭터",
    description: "미니멀 장난감 3D 로봇",
    tags: ["3D", "로봇", "장난감", "미니멀"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "img-3d-5",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#입체 퐁퐁이 아일랜드",
    prompt_text: "구름 위에 떠있는 아기자기한 3D 장난감 마을과 무지개 동산",
    description: "구름 위 3D 장난감 마을과 무지개",
    tags: ["3D", "동화", "구름", "무지개"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "img-3d-6",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 금융 백그라운드",
    prompt_text: "파스텔 톤 동전과 황금 열쇠가 날아다니는 금융 앱 3D 일러스트",
    description: "금융 핀테크 앱용 파스텔 3D 배경",
    tags: ["3D", "금융", "핀테크", "파스텔"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "img-3d-7",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 귀여운 디저트",
    prompt_text: "딸기 생크림 케이크와 알록달록 마카롱이 떠있는 3D 렌더링",
    description: "알록달록 3D 디저트 마카롱 케이크",
    tags: ["3D", "디저트", "케이크", "마카롱"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "img-3d-8",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 우주선 비행",
    prompt_text: "알록달록한 아기 우주선이 반짝이는 별들 사이를 누비는 3D 그래픽",
    description: "우주선 비행 3D 그래픽",
    tags: ["3D", "우주선", "별", "그래픽"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "img-3d-9",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 스마트 홈",
    prompt_text: "미니멀 아이콘 형태의 스마트 TV와 온도조절기가 조화를 이루는 3D 아트",
    description: "스마트 홈 가전 3D 미니멀 아이콘",
    tags: ["3D", "스마트홈", "가전", "미니멀"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "img-3d-10",
    program_slug: "ai-image-studio",
    category: "3D 디지털 아트",
    title: "#3D 동물 동화 캐릭터",
    prompt_text: "책 읽는 귀여운 3D 아기 곰돌이 캐릭터, 부드러운 3D 질감",
    description: "동화 속 책 읽는 아기 곰돌이 3D",
    tags: ["3D", "곰돌이", "동화", "캐릭터"],
    is_active: true,
    sort_order: 10,
  },

  // 3. 감성 패션 화보 (10개)
  {
    id: "img-fashion-1",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#패션 룩북 화보",
    prompt_text: "모던한 미니멀 백그라운드 스튜디오에서 봄 신상 트렌치코트를 입은 모델의 패션 잡지 화보",
    description: "트렌치코트 봄 룩북 잡지 화보",
    tags: ["패션", "룩북", "트렌치코트", "잡지"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "img-fashion-2",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#보그 흑백 세련미",
    prompt_text: "Vogue 룩북 스타일, 드라마틱한 음영 대비가 돋보이는 모던 하이패션 포즈의 여성 모델",
    description: "Vogue 흑백 하이패션 화보 포즈",
    tags: ["패션", "Vogue", "흑백", "하이패션"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "img-fashion-3",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#하이엔드 주얼리 컷",
    prompt_text: "고급스러운 아크릴 무대 위 다이아몬드 목걸이와 패션 잡지 커버컷 조명 연출",
    description: "다이아몬드 목걸이 커버 컷 조명",
    tags: ["패션", "주얼리", "다이아몬드", "커버컷"],
    is_active: true,
    sort_order: 3,
  },
  {
    id: "img-fashion-4",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#네온 스트리트 패션",
    prompt_text: "밤거리 도심 속 힙한 스트릿웨어와 선글라스를 착용한 모델의 감성 화보",
    description: "도심 밤거리 힙합 스트리트 패션",
    tags: ["패션", "스트릿웨어", "선글라스", "네온"],
    is_active: true,
    sort_order: 4,
  },
  {
    id: "img-fashion-5",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#미니멀 린넨 패션",
    prompt_text: "베이지 린넨 수트를 입은 한국 남성 모델의 차분하고 감성적인 인물 스냅",
    description: "린넨 수트 남성 인물 스냅",
    tags: ["패션", "린넨", "수트", "스냅"],
    is_active: true,
    sort_order: 5,
  },
  {
    id: "img-fashion-6",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#레트로 엘레강스",
    prompt_text: "70년대 클래식 무드의 드레스를 입은 모델과 레트로 가구 조화",
    description: "70년대 레트로 엘레강스 드레스",
    tags: ["패션", "레트로", "70년대", "드레스"],
    is_active: true,
    sort_order: 6,
  },
  {
    id: "img-fashion-7",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#컬러 블록 에디토리얼",
    prompt_text: "강렬한 레드와 블루 배경이 대조를 이루는 아방가르드 패션 화보",
    description: "레드 블루 강렬한 아방가르드 에디토리얼",
    tags: ["패션", "컬러블록", "아방가르드", "에디토리얼"],
    is_active: true,
    sort_order: 7,
  },
  {
    id: "img-fashion-8",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#하이패션 뷰티 포트레이트",
    prompt_text: "글로시한 입술과 매끈한 피부 디테일이 강조된 뷰티 매거진 커버 컷",
    description: "매끈 피부 뷰티 매거진 커버 컷",
    tags: ["패션", "뷰티", "포트레이트", "매거진"],
    is_active: true,
    sort_order: 8,
  },
  {
    id: "img-fashion-9",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#스튜디오 그림자 예술",
    prompt_text: "블라인드 사이로 새어 나오는 슬릿 조명과 인물의 감각적인 실루엣",
    description: "블라인드 실루엣 슬릿 조명 화보",
    tags: ["패션", "조명", "실루엣", "그림자"],
    is_active: true,
    sort_order: 9,
  },
  {
    id: "img-fashion-10",
    program_slug: "ai-image-studio",
    category: "감성 패션 화보",
    title: "#실크 드레스 댄스",
    prompt_text: "바람에 흩날리는 붉은 실크 드레스를 입고 무용하는 모델의 역동적인 컷",
    description: "붉은 실크 드레스 역동적 댄스",
    tags: ["패션", "실크드레스", "무용", "역동적"],
    is_active: true,
    sort_order: 10,
  },

  // 4. 벡터 일러스트 (10개)
  {
    id: "img-vec-1",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#벡터 제품 일러스트",
    prompt_text: "친환경 오가닉 코스메틱 화장품 병과 나뭇잎 요소가 조화로운 벡터 평면 일러스트레이션",
    description: "오가닉 화장품 백터 일러스트",
    tags: ["벡터", "화장품", "오가닉", "일러스트"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "img-vec-2",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#IT 스타트업 캐릭터",
    prompt_text: "노트북으로 코딩 중인 젊은 개발자 팀, 선명한 아웃라인과 모던 벡터 스타일",
    description: "개발자 코딩 모던 벡터 캐릭터",
    tags: ["벡터", "스타트업", "코딩", "개발자"],
    is_active: true,
    sort_order: 2,
  },
  {
    id: "img-vec-3",
    program_slug: "ai-image-studio",
    category: "벡터 일러스트",
    title: "#도시 생활 플랫 카드",
    prompt_text: "커피를 들고 도심 공원을 산책하는 사람들의 세련된 flat vector 그래픽",
    description: "도심 공원 산책 flat vector",
    tags: ["벡터", "플랫아트", "산책", "공원"],
    is_active: true,
    sort_order: 3,
  },

  // 5. 사이버펑크 네온 (10개)
  {
    id: "img-cyber-1",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#사이버펑크 서울야경",
    prompt_text: "네온사인 가득한 비 내리는 사이버펑크 서울 야경 속 트렌디한 한국 여성의 몽환적인 포트레이트",
    description: "비 내리는 서울 야경 네온 포트레이트",
    tags: ["사이버펑크", "서울야경", "네온", "포트레이트"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "img-cyber-2",
    program_slug: "ai-image-studio",
    category: "사이버펑크 네온",
    title: "#네온 라이더 스피드",
    prompt_text: "미래도시 네온 고속도로를 질주하는 사이버펑크 오토바이 라이더와 청색/자홍색 이펙트",
    description: "사이버펑크 오토바이 질주 이펙트",
    tags: ["사이버펑크", "오토바이", "고속도로", "라이더"],
    is_active: true,
    sort_order: 2,
  },

  // 6. 동양 수묵화 (10개)
  {
    id: "img-ink-1",
    program_slug: "ai-image-studio",
    category: "동양 수묵화",
    title: "#수묵 한복 포트레이트",
    prompt_text: "은은한 수묵 먹선과 한지 질감 속 아련한 분위기의 한복 입은 선비와 매화 가지",
    description: "한지 수묵 먹선 한복 선비",
    tags: ["수묵화", "한복", "동양화", "매화"],
    is_active: true,
    sort_order: 1,
  },

  // 7. 수채화 파스텔 (10개)
  {
    id: "img-water-1",
    program_slug: "ai-image-studio",
    category: "수채화 파스텔",
    title: "#수채화 파스텔 동화",
    prompt_text: "해질녘 분홍빛 노을 하늘 아래 동화 속 작은 목조 오두막과 꽃밭 풍경",
    description: "분홍 노을 동화 오두막 수채화",
    tags: ["수채화", "파스텔", "동화", "오두막"],
    is_active: true,
    sort_order: 1,
  },

  // 8. 35mm 필름 (10개)
  {
    id: "img-film-1",
    program_slug: "ai-image-studio",
    category: "35mm 필름",
    title: "#35mm 빈티지 카페",
    prompt_text: "80년대 골목길 카페 야외 테라스에서 커피를 마시는 감성적인 빈티지 인물 컷",
    description: "80년대 골목 테라스 빈티지 인물 컷",
    tags: ["필름", "35mm", "빈티지", "카페"],
    is_active: true,
    sort_order: 1,
  },

  // 9. 클레이 스톱모션 (10개)
  {
    id: "img-clay-1",
    program_slug: "ai-image-studio",
    category: "클레이 스톱모션",
    title: "#지점토 귀여운 공룡",
    prompt_text: "손맛 느껴지는 울퉁불퉁 지점토 질감의 알록달록 아기 공룡 스톱모션 인형",
    description: "지점토 울퉁불퉁 아기 공룡 인형",
    tags: ["클레이", "스톱모션", "지점토", "공룡"],
    is_active: true,
    sort_order: 1,
  },

  // 10. 웹툰 라인아트 (10개)
  {
    id: "img-toon-1",
    program_slug: "ai-image-studio",
    category: "웹툰 라인아트",
    title: "#웹툰 주인공 액션",
    prompt_text: "강렬한 먹선 아웃라인과 셀 셰이딩이 돋보이는 한국 판타지 웹툰 주인공 소환 씬",
    description: "판타지 웹툰 주인공 먹선 아웃라인",
    tags: ["웹툰", "라인아트", "판타지", "먹선"],
    is_active: true,
    sort_order: 1,
  },

  // 11. 건축 & 인테리어 (10개)
  {
    id: "img-arch-1",
    program_slug: "ai-image-studio",
    category: "건축 & 인테리어",
    title: "#건축 인테리어",
    prompt_text: "통창 너머로 숲이 펼쳐지는 미니멀 우드 앤 콘크리트 고급 거실 인테리어 디자인",
    description: "통창 미니멀 콘크리트 고급 거실",
    tags: ["건축", "인테리어", "미니멀", "거실"],
    is_active: true,
    sort_order: 1,
  },

  // 12. 다크 판타지 (10개)
  {
    id: "img-dark-1",
    program_slug: "ai-image-studio",
    category: "다크 판타지",
    title: "#다크판타지 웅장함",
    prompt_text: "어둡고 신비로운 고성 타워 위에서 붉은 마법 룬을 시전하는 검은 로브의 마법사",
    description: "신비로운 고성 마법 룬 마법사",
    tags: ["다크판타지", "고성", "마법사", "룬"],
    is_active: true,
    sort_order: 1,
  },

  // 13. 미니멀 플랫 아트 (10개)
  {
    id: "img-flat-1",
    program_slug: "ai-image-studio",
    category: "미니멀 플랫 아트",
    title: "#미니멀 여행 포스터",
    prompt_text: "제주 돌하르방과 조용한 해변을 감각적인 컬러 블록으로 표현한 모던 아트 포스터",
    description: "제주 해변 감각적 컬러 블록 포스터",
    tags: ["미니멀", "플랫아트", "포스터", "제주"],
    is_active: true,
    sort_order: 1,
  },

  // 타 서브프로젝트 샘플 (블로그, 쓰레드, 음악 등)
  {
    id: "blog-1",
    program_slug: "ai-auto-blog",
    category: "SEO 가이드",
    title: "초보자 가이드 작성",
    prompt_text: "당신은 전문 IT 기술 블로거입니다. '{keyword}'에 대해 SEO 구조로 제목과 서론, 본문 3가지 팁, 결론을 작성하세요.",
    description: "SEO 블로그 원문 작성 템플릿",
    tags: ["SEO", "블로그", "가이드"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "threads-1",
    program_slug: "auto-threads-posting",
    category: "바이럴 숏폼",
    title: "직장인 공감 텍스트",
    prompt_text: "Threads 바이럴 문구를 만듭니다. 가독성을 높인 숏폼 한글 텍스트와 명언 1줄로 마무리하세요.",
    description: "Threads 알고리즘 맞춤 숏폼",
    tags: ["Threads", "바이럴", "공감"],
    is_active: true,
    sort_order: 1,
  },
  {
    id: "music-1",
    program_slug: "music-automation",
    category: "K-POP 신스팝",
    title: "청량한 여름 밤 신스팝",
    prompt_text: "Upbeat Korean Synthpop, bright synthesizer melody, punchy bassline, catchy chorus, energetic vocal, 128 bpm",
    description: "Suno AI 프롬프트 예시",
    tags: ["Suno", "신스팝", "K-POP"],
    is_active: true,
    sort_order: 1,
  }
];
