import { Bell, BookOpenText, Check, FileText, ImageIcon, KeyRound, LayoutDashboard, PenLine, Search, Send, Tags } from 'lucide-react'

const steps = [
  ['1', '글감 수집', '트렌드·키워드에서 주제 후보를 모읍니다.', Search],
  ['2', 'AI 글쓰기', '원문·SEO 구조·이미지를 한 번에 만듭니다.', PenLine],
  ['3', '티스토리 입력', '확장 프로그램이 작성 화면에 안전하게 채웁니다.', Send],
] as const

export default function PreviewPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto flex min-h-screen max-w-[1600px]">
        <aside className="hidden w-72 shrink-0 border-r border-slate-200 bg-white p-5 lg:flex lg:flex-col">
          <div className="border-b border-slate-100 pb-5"><p className="text-lg font-black tracking-tight">티스토리(원문)생성 자동화</p><p className="mt-1 text-xs font-bold text-slate-400">v1.01 · 미리보기</p></div>
          <nav className="mt-5 space-y-2"><div className="flex items-center gap-3 rounded-xl bg-indigo-50 px-3 py-2.5 text-sm font-bold text-indigo-700"><LayoutDashboard size={17} /> 대시보드</div>{steps.map(([num, label, description, Icon]) => <div className="flex gap-3 rounded-xl px-2 py-2" key={num}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-100 text-sm font-extrabold text-slate-500">{num}</span><div><p className="flex items-center gap-1.5 text-sm font-bold"><Icon size={15} />{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div>)}</nav>
          <div className="mt-auto border-t border-slate-100 pt-4"><div className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm font-semibold text-slate-600"><KeyRound size={16} />API키등록·플랫폼연동</div></div>
        </aside>
        <section className="min-w-0 flex-1 p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl">
          <div className="mb-8 flex items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-indigo-50 px-3 py-1 text-xs font-extrabold text-indigo-700">TISTORY WORKFLOW</span><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">원문 생성부터 티스토리 입력까지</h1><p className="mt-3 text-sm leading-6 text-slate-500">BLOG(원문)생성 자동화와 같은 글쓰기 흐름에 티스토리 전용 입력 단계를 연결합니다.</p></div><div className="hidden rounded-2xl border border-indigo-100 bg-white p-3 text-indigo-600 shadow-sm sm:block"><Bell size={20} /></div></div>
          <div className="mb-7 grid gap-3 md:grid-cols-3">{steps.map(([num, label, description, Icon], index) => <div className={`rounded-2xl border p-5 shadow-sm ${index === 2 ? 'border-indigo-200 bg-indigo-600 text-white' : 'border-slate-200 bg-white'}`} key={num}><div className="flex items-center justify-between"><span className={`text-xs font-black ${index === 2 ? 'text-indigo-100' : 'text-indigo-600'}`}>STEP {num}</span><Icon size={19} /></div><p className="mt-4 font-extrabold">{label}</p><p className={`mt-1 text-xs leading-5 ${index === 2 ? 'text-indigo-100' : 'text-slate-500'}`}>{description}</p></div>)}</div>
          <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="text-lg font-black">AI 글쓰기</p><p className="mt-1 text-xs text-slate-500">주제와 키워드를 바탕으로 티스토리용 원문 초안을 만듭니다.</p></div><PenLine className="text-indigo-600" size={22} /></div><div className="mt-6 space-y-5"><label className="block text-sm font-bold">블로그 주제 <span className="text-rose-500">*</span><div className="mt-2 rounded-xl border-2 border-slate-200 px-4 py-3 text-sm font-medium text-slate-400">예: 1인 사업자를 위한 티스토리 SEO 글쓰기 가이드</div></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">글 분위기<div className="mt-2 rounded-xl border-2 border-slate-200 px-4 py-3 text-sm font-medium text-slate-600">친근하고 전문적인</div></label><label className="text-sm font-bold">목표 분량<div className="mt-2 rounded-xl border-2 border-slate-200 px-4 py-3 text-sm font-medium text-slate-600">1,500 단어</div></label></div><div><p className="text-sm font-bold">SEO 키워드</p><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700">#티스토리 SEO</span><span className="rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700">#블로그 자동화</span><span className="rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700">#원문 생성</span></div></div><div className="rounded-2xl border border-amber-100 bg-amber-50/70 p-4 text-xs leading-5 text-amber-900"><b>이미지 생성</b> · 회원님이 등록한 Gemini API 키로 본문 이미지까지 함께 준비합니다.</div><button className="flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 py-4 text-sm font-extrabold text-white shadow-lg shadow-indigo-200"><FileText size={18} />AI 글 생성 시작</button></div></div>
          <div className="space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Send className="text-indigo-600" size={20} /><p className="font-black">티스토리 입력 단계</p></div><ol className="mt-5 space-y-4 text-sm">{['티스토리 글쓰기 화면을 엽니다.', '확장 프로그램에서 생성 글을 선택합니다.', '제목·본문·이미지·태그를 입력합니다.', '내용을 확인한 뒤 회원님이 직접 발행합니다.'].map((item, i) => <li className="flex gap-3" key={item}><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-xs font-black text-indigo-700">{i + 1}</span><span className="leading-6 text-slate-600">{item}</span></li>)}</ol><div className="mt-5 rounded-xl bg-slate-50 p-3 text-xs font-semibold leading-5 text-slate-500">최종 발행은 자동으로 누르지 않습니다. 입력된 내용을 티스토리에서 확인한 뒤 직접 진행합니다.</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ImageIcon className="text-indigo-600" size={20} /><p className="font-black">생성 결과 미리보기</p></div><div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><BookOpenText className="mx-auto text-slate-300" size={32} /><p className="mt-3 text-sm font-bold text-slate-500">글을 생성하면 이곳에서 확인합니다.</p></div></div><div className="rounded-3xl border border-indigo-100 bg-indigo-50 p-5"><p className="flex items-center gap-2 text-sm font-black text-indigo-900"><Tags size={18} />티스토리 전용 준비 상태</p><p className="mt-2 text-xs leading-5 text-indigo-800">확장 프로그램은 실제 글쓰기 화면 구조를 점검 중입니다. 입력 기능은 점검 결과를 반영해 안전하게 이어서 제공합니다.</p><div className="mt-3 flex items-center gap-2 text-xs font-bold text-indigo-700"><Check size={15} />원문 생성 화면 완료</div></div></div></div>
        </div></section>
      </div>
    </main>
  )
}
