const status=document.querySelector('#status');
async function action(type, extra={}) { const r=await chrome.runtime.sendMessage({type,...extra}); if(r?.error) throw new Error(r.error); return r; }
function showUpdate(update){ const box=document.querySelector('#update'); if(!update?.outdated||!String(update.downloadUrl||'').startsWith('https://naver-blog-agent.vercel.app/')){box.hidden=true;return;} document.querySelector('#updateText').textContent=`설치된 버전 ${update.current} → 최신 ${update.latest}`; document.querySelector('#updateLink').href=update.downloadUrl; box.hidden=false; }
async function refresh(){ const {connection,session,connectionError,update,lastPrepared,activeTask,recovery,resultConflicts}=await action('status'); showUpdate(update); const ready=Boolean(lastPrepared && connection?.blogId===lastPrepared.blogId); document.querySelector('#openPrepared').hidden=!ready; const note=document.querySelector('#preparedStatus'); note.hidden=!ready; note.textContent=ready?`발행 전 준비 완료: ${lastPrepared.title || '원고'} · 최종 버튼은 누르지 않았습니다. 열린 네이버 원고를 확인해 주세요.`:''; status.textContent=connection?`${connection.label} · ${connection.blogId}\n${connectionError || (recovery?'이전 실행 수신 확인이 없습니다. 보관함에서 네이버 결과 확인 후 복구해 주세요.':activeTask?`작업 진행: ${activeTask.stage} · ${activeTask.runId || '기존 실행'}`:resultConflicts?.length?`이전 실행 결과 ${resultConflicts.length}건이 별도로 보관되어 있습니다. 보관함과 네이버 결과를 확인해 주세요.`:(session?.reason || '연결되었습니다. 상태를 확인해 주세요.'))}`:'아직 연결되지 않았습니다. 앱에서 코드를 발급받으세요.'; }
document.querySelector('#pairForm').onsubmit=async e=>{e.preventDefault();try {status.textContent='연결 중…';await action('pair',{code:document.querySelector('#code').value.trim(),blogId:document.querySelector('#blogId').value.trim()});document.querySelector('#code').value='';await action('session');await refresh();}catch(e){status.textContent=e.message;}};
document.querySelector('#login').onclick=async()=>{try{status.textContent='열린 블로그 화면에서 로그인하면 자동으로 확인합니다.';await action('session');await refresh();}catch(e){status.textContent=e.message;}};
document.querySelector('#disconnect').onclick=async()=>{try{await action('disconnect');await refresh();}catch(e){status.textContent=e.message;}};
action('checkUpdate').then(r=>showUpdate(r.update)).catch(()=>{}); refresh().catch(e=>status.textContent=e.message); setInterval(()=>refresh().catch(()=>{}),5000);

document.querySelector('#openPrepared').onclick=async()=>{try{await action('openPrepared');}catch(e){status.textContent=e.message;}};
