"use strict";
const BASE="https://naver-blog-seo-studio.vercel.app", KEY="seoStudioToken";
const $=id=>document.getElementById(id);
async function stored(){return (await chrome.storage.local.get(KEY))[KEY]||""}
async function verify(token){if(!token)return {ok:false,error:"토큰을 입력하세요."};try{const r=await fetch(`${BASE}/api/extension/whoami`,{headers:{Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>({}));return r.ok?{ok:true,email:b.email}:{ok:false,error:b.error||`연결 실패 (${r.status})`}}catch(e){return {ok:false,error:e.message}}}
async function render(){const t=await stored();const r=await verify(t);$("status").textContent=r.ok?`연결됨: ${r.email}`:(t?`오류: ${r.error}`:"연결되지 않음")}
$("link").addEventListener("click",async()=>{const t=$("token").value.trim();$("link").disabled=true;const r=await verify(t);if(r.ok){await chrome.storage.local.set({[KEY]:t});$("token").value=""}$("link").disabled=false;$("status").textContent=r.ok?`연결됨: ${r.email}`:`오류: ${r.error}`});
$("generate").addEventListener("click",async()=>{const t=await stored(),topic=$("topic").value.trim();if(!t)return $("generateStatus").textContent="먼저 SEO Studio를 연결하세요.";if(!topic)return $("generateStatus").textContent="주제를 입력하세요.";$("generate").disabled=true;$("generateStatus").textContent="초안을 생성하는 중입니다...";try{const r=await fetch(`${BASE}/api/extension/drafts`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({topic,keywords:$("keywords").value,strategy:"C-Rank 기본"})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||`생성 실패 (${r.status})`);$("title").value=b.title||"";$("body").value=b.body||"";$("generateStatus").textContent="초안 생성 완료"}catch(e){$("generateStatus").textContent=`오류: ${e.message}`}finally{$("generate").disabled=false}});
$("fill").addEventListener("click",async()=>{const title=$("title").value,body=$("body").value;if(!title&&!body)return $("generateStatus").textContent="먼저 초안을 생성하세요.";const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!/^https:\/\/(blog|m\.blog)\.naver\.com/.test(tab.url||""))return $("generateStatus").textContent="네이버 블로그 글쓰기 화면을 먼저 여세요.";await chrome.scripting.executeScript({target:{tabId:tab.id},args:[title,body],func:(t,b)=>{const titleEl=document.querySelector('input[placeholder*="제목"],input.se_textarea');const bodyEl=document.querySelector('[contenteditable="true"]');if(titleEl){titleEl.value=t;titleEl.dispatchEvent(new Event('input',{bubbles:true}))}if(bodyEl){bodyEl.focus();bodyEl.innerHTML=b.replace(/\n/g,"<br>");bodyEl.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:b}))}return Boolean(titleEl||bodyEl)}});$("generateStatus").textContent="네이버 편집기에 입력했습니다."});
render();
